#!/usr/bin/env perl


use utf8;
use strict;
use warnings;

use JSON;
use JSON::Types;
use Getopt::Long;
use Text::CSV;

my $num = [];
GetOptions ("num=s@" => \$num);
@$num = split(/,/,join(',',@$num));

my $csv = Text::CSV->new ( { binary => 1 } );
my @name;
my @data;
while ( my $line = <STDIN> ) {
    chomp($line);
    next unless $line;
    $csv->parse( $line );
    if ( @name ) {
        my @columns = $csv->fields();
        my $hash;
        for my $i ( keys @name ){
            if ( $name[$i] ) {
                if ( grep { /^$name[$i]$/ } @$num ) {
                    $hash->{ $name[$i] } = number $columns[$i];
                }
                else {
                    $hash->{ $name[$i] } = $columns[$i];
                }
            }
        }
        push @data, $hash;
    }
    else {
         @name = $csv->fields();
    }
}

my $json_text = encode_json \@data;;
print $json_text;

