#!/usr/bin/env perl


use utf8;
use strict;
use warnings;

use Text::CSV;
use JSON;

my $csv = Text::CSV->new ( { binary => 1 } );
my @name;
my @data;
while ( my $line = <STDIN> ) {
    $csv->parse( $line );
    if ( @name ) {
        my @columns = $csv->fields();
        my $hash;
        for my $i ( keys @name ){
            $hash->{ $name[$i] } = $columns[$i] if $name[$i];
        }
        push @data, $hash;
    }
    else {
         @name = $csv->fields();
    }
}

my $json_text = encode_json \@data;;

print $json_text;

