#!/usr/bin/env perl

use utf8;
use strict;
use warnings;
use Text::CSV;
use Data::Dumper;

local $Data::Dumper::Indent = 1;
local $Data::Dumper::Terse  = 1;

my $csv = Text::CSV->new ( { binary => 1 } );
my @name;
my @data;
while ( my $line = <STDIN> ) {
    chomp($line);
    $csv->parse( $line );
    if ( @name ) {
        my @columns = $csv->fields();
        my $hash;
        for my $i ( keys @name ){
            $hash->{ $name[$i] } = $columns[$i] if $name[$i];
        }
        push @data, $hash;
    }
    else {
         @name = $csv->fields();
    }
}

print Dumper(\@data);

