#!/usr/bin/env perl

use utf8;
use strict;
use warnings;
use Text::LTSV;
use Data::Dumper;

local $Data::Dumper::Indent = 1;
local $Data::Dumper::Terse  = 1;

my $p = Text::LTSV->new;

my @data;
while ( my $line = <STDIN> ) {
    chomp($line);
    push @data, $p->parse_line($line);
}

print Dumper(\@data);
