#!/usr/bin/env perl

use utf8;
use strict;
use warnings;
use Text::LTSV;
use JSON;

my $p = Text::LTSV->new;

my @data;
while ( my $line = <STDIN> ) {
    chomp($line);
    push @data, $p->parse_line($line);
}

my $json_text = encode_json \@data;;

print "$json_text";

