#!/usr/bin/env perl

use utf8;
use strict;
use warnings;
use JSON;

my @name;
my @data;
while ( my $line = <STDIN> ) {
    chomp($line);
    my @columns = split("\t", $line);
    if ( @name ) {
        my $hash;
        for my $i ( keys @name ){
            $hash->{ $name[$i] } = $columns[$i] if $name[$i];
        }
        push @data, $hash;
    }
    else {
         @name = @columns;
    }
}
my $json_text = encode_json \@data;;

print "$json_text";
