#!/usr/bin/env perl

use utf8;
use strict;
use warnings;

use JSON;
use JSON::Types;
use Getopt::Long;

my $int = [];
GetOptions ("int=s@" => \$int);
@$int = split(/,/,join(',',@$int));

my @name;
my @data;
while ( my $line = <STDIN> ) {
    chomp($line);
    my @columns = split("\t", $line);
    if ( @name ) {
        my $hash;
        for my $i ( keys @name ){
            if ( $name[$i] ) {
                if ( grep { /^$name[$i]$/ } @$int ) {
                    $hash->{ $name[$i] } = number $columns[$i];
                }
                else {
                    $hash->{ $name[$i] } = $columns[$i];
                }
            }
        }
        push @data, $hash;
    }
    else {
         @name = @columns;
    }
}
my $json_text = encode_json \@data;;

print "$json_text";
